# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlroom', '0005_auto_20170802_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_list',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
