# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlroom', '0006_event_short_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_list',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
