# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlroom', '0007_auto_20170809_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='em_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='em_num_1',
        ),
        migrations.AlterField(
            model_name='event',
            name='em_1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='em_num_2',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
