# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlroom', '0014_auto_20170921_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
